### ISSUE TITLE
Desenvolver tela dashboard

### ISSUE THREAD

**Issue by AlissonDiogo** [RamonJales/bora-pagar-shippuden#60]
Desenvolver a tela de gerenciar-semestre

![image](https://github.com/user-attachments/assets/b54cc16d-c30c-4c82-b54f-011703f54e79)
Se basear no figma, pois o layout pode ser alterado

**Todos os dados são estáticos** 

- [ ] Componentes bem definidos e separados
- [ ] Ao criar os componentes definir as cores para o light e dark modes, exemplo: `<div class="bg-white dark:bg-black">`
- [ ] A url pode ser /dashboard ou /gerenciar-semestre
- [ ] Não fazer a Navbar (a que aparece no print), será feito em uma outra issue
