### ISSUE TITLE
Desenvolver tela consultar disciplinas

### ISSUE THREAD

**Issue by AlissonDiogo** [RamonJales/bora-pagar-shippuden#61]
Desenvolver a tela de consultar-disciplinas

![image](https://github.com/user-attachments/assets/c73fb7d1-aac3-41d9-8cd2-f3b594254c61)
Se basear no figma, pois o layout pode ser alterado

**Todos os dados são estáticos** 

- [ ] Componentes bem definidos e separados
- [ ] Ao criar os componentes definir as cores para o light e dark modes, exemplo: `<div class="bg-white dark:bg-black">`
- [ ] A url pode ser /consultar-disciplinas ou /consultar-materias
- [x] Não fazer a Navbar (a que aparece no print), será feito em uma outra issue
